name: greenhouse

services:

  device-runtime-image:
    build:
      context: ..
      dockerfile: docker/device-runtime.Dockerfile
    image: docker-device-runtime
    container_name: greenhouse_device_runtime_image
    restart: "no"
    command: ["sh", "-c", "echo device runtime image built; exit 0"]

  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: greenhouse_mqtt_broker
    ports:
      - "1883:1883"
    networks:
      - default
      - greenhouse_iot_net

  postgres:
    image: postgres:15
    container_name: greenhouse_postgres
    environment:
      POSTGRES_USER: greenhouse
      POSTGRES_PASSWORD: greenhouse
      POSTGRES_DB: greenhouse
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U greenhouse -d greenhouse"]
      interval: 2s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: greenhouse_backend
    depends_on:
      postgres:
        condition: service_healthy
      mqtt-broker:
        condition: service_started
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      # - SQL_ECHO=true
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=1883
    volumes:
      - ../backend:/app
    networks:
      - default
      - greenhouse_iot_net

  frontend-dashboard:
    build:
      context: ..
      dockerfile: docker/frontend-dashboard.Dockerfile
    container_name: greenhouse_frontend_dashboard
    depends_on:
      - backend
    ports:
      - "3000:5173"
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes:
      - /app/node_modules
      - ../frontend-dashboard:/app

  frontend-device-config:
    build:
      context: ..
      dockerfile: docker/frontend-device-config.Dockerfile
    container_name: greenhouse_frontend_device_config
    depends_on:
      - backend
    ports:
      - "3001:5174"
    command: npm run dev -- --host 0.0.0.0 --port 5174
    volumes:
      - /app/node_modules
      - ../frontend-device-config:/app

  sensor-emulator-manager:
    build:
      context: ..
      dockerfile: docker/sensor-manager.Dockerfile
    container_name: greenhouse_sensor_emulator_manager
    depends_on:
      device-runtime-image:
        condition: service_completed_successfully
      backend:
        condition: service_started
      mqtt-broker:
        condition: service_started
    environment:
      - BACKEND_URL=http://backend:8000
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=1883
      - POLL_INTERVAL_SECONDS=5
      - HEALTHCHECK_INTERVAL_SECONDS=10
      - STATE_FILE_PATH=/state/state.json
      - DEVICE_NETWORK_NAME=greenhouse_iot_net
      - DEVICE_IMAGE=docker-device-runtime
      - DEVICE_GROUP_PROJECT=devices
      - DEVICE_GROUP_SERVICE=device-runtime
      - SENSOR_IP_RANGE=172.28.1.10-172.28.1.250
      - ACTUATOR_IP_RANGE=172.28.2.10-172.28.2.250
      - AUTO_RESTART_MAX_RETRIES=5
      - STOP_TIMEOUT_SECONDS=10
    volumes:
      - ../device-emulator:/state
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - greenhouse_iot_net

volumes:
  postgres_data:

networks:
  greenhouse_iot_net:
    name: greenhouse_iot_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16