listener 1883
listener_allow_anonymous false
password_file /mosquitto/data/passwords
acl_file /mosquitto/data/acl.conf

listener 8883
listener_allow_anonymous false
password_file /mosquitto/data/passwords
acl_file /mosquitto/data/acl.conf
cafile /mosquitto/data/certs/ca.crt
certfile /mosquitto/data/certs/server.crt
keyfile /mosquitto/data/certs/server.key
require_certificate false

persistence true
persistence_location /mosquitto/data/

log_type error
log_type warning
log_type notice
log_type information
