listener 1883
listener_allow_anonymous false
password_file /mosquitto/data/passwords
acl_file /mosquitto/config/acl.conf

persistence true
persistence_location /mosquitto/data/

log_type error
log_type warning
log_type notice
log_type information
