listener 8883
listener_allow_anonymous true
acl_file /mosquitto/data/acl.conf
cafile /mosquitto/data/certs/device-ca.crt
certfile /mosquitto/data/certs/server.crt
keyfile /mosquitto/data/certs/server.key
require_certificate true
use_identity_as_username true

persistence true
persistence_location /mosquitto/data/

log_type error
log_type warning
log_type notice
log_type information
